# Generated by Django 4.0.6 on 2024-02-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummyUSER',
        ),
    ]
