# Generated by Django 4.0.6 on 2024-03-04 18:42

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_skillsgroup_skills_skillsgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skillsgroup',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skillsof',
        ),
        migrations.CreateModel(
            name='BuildSkillSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(default=None, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='skills.slug')),
                ('skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.skills')),
                ('skillsgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.skillsgroup')),
                ('skillsof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.skillsof')),
            ],
        ),
    ]
