# Generated by Django 4.0.6 on 2024-03-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_skills_skillsgroup_remove_skills_skillsof_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildSkillSets',
            new_name='SkillSetsBuild',
        ),
    ]
