# Generated by Django 4.0.6 on 2024-04-06 18:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theLearnings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('slugs', models.TextField(blank=True, default=None, null=True)),
                ('tags', models.TextField(blank=True, default=None, null=True)),
                ('extensions', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('discription', models.TextField(blank=True, default=None, null=True)),
                ('skillsof', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.skillof')),
            ],
        ),
    ]
