# Generated by Django 4.0.6 on 2024-04-06 19:11

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_options_optionsof'),
        ('theLearnings', '0002_programminglanguages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('slugs', models.TextField(blank=True, default=None, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSubHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('slugs', models.TextField(blank=True, default=None, null=True)),
                ('headings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.topicheadings')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('slugs', models.TextField(blank=True, default=None, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('discription', models.TextField(blank=True, default=None, null=True)),
                ('joiningdate', models.DateTimeField(auto_now_add=True)),
                ('updationdate', models.DateTimeField(auto_now=True)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.user')),
                ('headings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.topicheadings')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.skill')),
                ('subheadings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.topicsubheadings')),
            ],
        ),
    ]
