# Generated by Django 4.0.6 on 2024-04-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theLearnings', '0003_topicheadings_topicsubheadings_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
