# Generated by Django 4.0.6 on 2024-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theLearnings', '0004_skill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.TextField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
