# Generated by Django 4.0.6 on 2024-08-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theLearnings', '0007_alter_topic_title_alter_topicheadings_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicheadings',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.skill'),
        ),
    ]
