# Generated by Django 4.0.6 on 2024-08-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theLearnings', '0007_alter_topic_headings_alter_topicheadings_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='headings',
            field=models.ForeignKey(blank=True, limit_choices_to={'skill__skill': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.skill')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theLearnings.topicheadings'),
        ),
    ]
