# Generated by Django 4.0.6 on 2024-03-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('discription', models.TextField(default=None, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default=None, max_length=50, null=True)),
                ('FirstName', models.CharField(default=None, max_length=25, null=True)),
                ('LastName', models.CharField(default=None, max_length=25, null=True)),
                ('Username', models.CharField(max_length=30)),
                ('Mobile', models.IntegerField(default=None, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Profile', models.ImageField(default=None, null=True, upload_to='_user/_profiles/')),
                ('isChecked', models.BooleanField(default=False, null=True)),
                ('isActive', models.BooleanField(default=False, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What', models.CharField(choices=[('Report', 'Report'), ('Suggestion', 'Suggestion'), ('Ask', 'Ask')], max_length=25)),
                ('Status', models.CharField(choices=[('Activated', 'Activated'), ('Declined', 'Declined'), ('Resolved', 'Resolved')], default='Activated', max_length=25)),
                ('From', models.CharField(choices=[('Artical', 'Artical'), ('Problem', 'Problem'), ('Youtube', 'Youtube')], max_length=25)),
                ('Type', models.CharField(choices=[('Add Link', 'Add Link'), ('Missleading Content', 'Missleading Content'), ('Verify Content', 'Verify Content'), ('Others', 'Others')], default='Others', max_length=100)),
                ('Title', models.CharField(default=None, max_length=50, null=True)),
                ('Content', models.TextField(default=None, null=True)),
                ('Discription', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(default=None, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Home.actions')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Home.user')),
            ],
        ),
    ]
