# Generated by Django 4.0.6 on 2024-02-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('discription', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default=None, max_length=50, null=True)),
                ('FirstName', models.CharField(default=None, max_length=25, null=True)),
                ('LastName', models.CharField(default=None, max_length=25, null=True)),
                ('Username', models.CharField(default=None, max_length=30, null=True)),
                ('MobileNumber', models.IntegerField(default=None, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Profile', models.ImageField(upload_to='user/')),
                ('isChecked', models.BooleanField(default=False, null=True)),
                ('isActive', models.BooleanField(default=False, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.action')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.user')),
            ],
        ),
    ]
