# Generated by Django 4.0.6 on 2024-02-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='discription',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='discription',
            field=models.TextField(default=None, null=True),
        ),
    ]
