# Generated by Django 4.0.6 on 2024-02-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active',
            old_name='JoiningDate',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='active',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='checked',
            old_name='JoiningDate',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='checked',
            old_name='User',
            new_name='user',
        ),
    ]
