# Generated by Django 4.0.6 on 2024-02-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_action_discription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Actions',
        ),
    ]
