# Generated by Django 4.0.6 on 2024-02-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_action_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='MobileNumber',
            new_name='Mobile',
        ),
    ]
