# Generated by Django 4.0.6 on 2024-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_mobilenumber_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.ImageField(default='user/default.jpeg', null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=30),
        ),
    ]
