# Generated by Django 4.0.6 on 2024-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.ImageField(default='/_user/_profiles/_default.jpeg', null=True, upload_to='_user/_profiles/'),
        ),
    ]
