# Generated by Django 4.0.6 on 2024-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.ImageField(default=None, null=True, upload_to='_user/_profiles/'),
        ),
    ]
