# Generated by Django 4.0.6 on 2024-02-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What', models.CharField(choices=[('Report', 'Report'), ('Suggestion', 'Suggestion'), ('Ask', 'Ask')], max_length=25)),
                ('Status', models.CharField(choices=[('Activated', 'Activated'), ('Declined', 'Declined'), ('Resolved', 'Resolved')], default='Activated', max_length=25)),
                ('From', models.CharField(choices=[('Artical', 'Artical'), ('Problem', 'Problem'), ('Youtube', 'Youtube')], max_length=25)),
                ('Type', models.CharField(choices=[('Add Link', 'Add Link'), ('Missleading Content', 'Missleading Content'), ('Verify Content', 'Verify Content'), ('Others', 'Others')], default='Others', max_length=100)),
                ('Title', models.CharField(default=None, max_length=50, null=True)),
                ('Content', models.TextField(default=None, null=True)),
                ('Discription', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.user')),
            ],
        ),
    ]
