# Generated by Django 4.0.6 on 2024-03-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        ('theArticals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articals',
            name='SkillSetsBuild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.skillsetsbuild'),
        ),
    ]
