# Generated by Django 4.0.6 on 2024-03-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_skillspointers'),
        ('theArticals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articals',
            name='SkillSetsBuild',
        ),
        migrations.AddField(
            model_name='articals',
            name='skillspointers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.skillspointers'),
        ),
    ]
