# Generated by Django 4.0.6 on 2024-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theArticals', '0002_remove_articals_skillsetsbuild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articals',
            name='discription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
