# Generated by Django 4.0.6 on 2024-02-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('url', models.CharField(default=None, max_length=50, null=True)),
                ('joiningdate', models.DateTimeField(auto_now_add=True)),
                ('updationdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HEADING_GROUPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('url', models.CharField(default=None, max_length=50, null=True)),
                ('joiningdate', models.DateTimeField(auto_now_add=True)),
                ('updationdate', models.DateTimeField(auto_now=True)),
                ('APP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.app')),
            ],
        ),
        migrations.CreateModel(
            name='ICONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('url', models.CharField(default=None, max_length=100, null=True)),
                ('size', models.CharField(default=None, max_length=100, null=True)),
                ('css', models.CharField(default=None, max_length=100, null=True)),
                ('joiningdate', models.DateTimeField(auto_now_add=True)),
                ('updationdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HEADING_NAMES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('url', models.CharField(default=None, max_length=50, null=True)),
                ('joiningdate', models.DateTimeField(auto_now_add=True)),
                ('updationdate', models.DateTimeField(auto_now=True)),
                ('APP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.app')),
                ('HEADING_GROUPS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.heading_groups')),
                ('ICONS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.icons')),
            ],
        ),
        migrations.AddField(
            model_name='heading_groups',
            name='ICONS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.icons'),
        ),
        migrations.AddField(
            model_name='app',
            name='ICONS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.icons'),
        ),
    ]
